variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Cache for analysis
  GIT_DEPTH: "0"  # Fetch full git history (needed by SonarCloud)

sonarcloud-check:
  image: maven:3-openjdk-17
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=s3-milan-van-steen
  only:
    - merge_requests
    - master
    - develop
