services:
  backend:
    image: milanvansteen/eventfinder-backend:latest
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;databaseName=eventfinder
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourStrong!Pass123
    depends_on:
      - mssql
    networks:
      - app-network

  frontend:
    image: milanvansteen/eventfinder-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
