global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

remote_write:
  - url: https://prometheus-blocks-prod-eu-west-0.grafana.net/api/prom/push
    basic_auth:
      username: <YOUR_INSTANCE_ID>
      password: <YOUR_GRAFANA_CLOUD_API_KEY>