###
GET http://localhost:8080/event/getAllEvents

<> 2025-05-21T173619.200.json
<> 2025-05-21T173545.200.json
<> 2025-05-21T173456.200.json

###
POST http://localhost:8080/event/createEvent
Content-Type: application/json

{
  "eventID": 2,
  "user": {"userID": 1},
  "name": "TestEvent2",
  "startDate": "",
  "endDate": "",
  "categories": []
}

<> 2025-05-21T173541.200.json

###
DELETE http://localhost:8080/event/deleteEvent?
    eventID=2

<> 2025-05-21T173616.200.txt

###
GET http://localhost:8080/event/getEventById?
    eventID=1

<> 2025-05-21T173627.200.json